spring:
  application:
    name: DatingProfile
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/dating-profiles-db
    username: postgres
    password: user